Fixed bad package version causing error when building simulator image
A messed up entry in PX4's requirements.txt would lead to the package "empy" being downloaded to the latest version, which would lead to the error: AttributeError: module 'em' has no attribute 'RAW_OPT'

We have fix this by overwriting the new package with the old one. See VMC/simulator/Dockerfile for more details.

Downloading the most recent release of PX4-Autopilot won't fix the issue, because they haven't packaged the commit (https://github.com/PX4/PX4-Autopilot/commit/3b041ef8d4f8493a166dcea0fb75ccca0e88b622) into a release. Have these fucking apes never heard of a hotfix before?